
import React from 'react';

export const CROP_DATASET_HINT = "N, P, K, pH, temperature, humidity, and rainfall are core factors for precision recommendation.";

export const MOCK_SENSORS = {
  n: 45,
  p: 52,
  k: 38,
  ph: 6.8,
  moisture: 22,
  temp: 28,
  humidity: 65,
  lastUpdated: new Date().toISOString()
};

export const getSystemInstruction = (lang: string) => `You are an Expert AI Agronomist. 
You provide scientific, practical, and highly accurate advice to farmers regarding crop health, 
soil management (NPK/pH levels), pest control, and sustainable farming. 
IMPORTANT: You MUST respond in the ${lang} language. 
Always be encouraging, professional, and clear. 
Use markdown for formatting. 
If sensor data is provided (N, P, K, pH), incorporate it into your diagnosis.`;

export const APP_THEME = {
  primary: 'emerald-600',
  secondary: 'amber-500',
  accent: 'blue-500',
  bg: 'slate-50'
};

export const TRANSLATIONS: Record<string, any> = {
  en: {
    appName: "AgriSmart AI",
    tagline: "Precision Agriculture Redefined",
    launch: "Launch Dashboard",
    health: "Farm Health",
    doctor: "Crop Doctor",
    predictor: "Predictor",
    market: "Market",
    advisor: "Advisor",
    overview: "Dashboard",
    farmers: "Farmers",
    campaigns: "Campaigns",
    repository: "Repository",
    nitrogen: "Nitrogen",
    phosphorus: "Phosphorus",
    potassium: "Potassium",
    soilPh: "Soil pH",
    moisture: "Moisture",
    temp: "Temperature",
    humidity: "Humidity",
    sync: "Sync IoT Sensors",
    syncing: "Linking ESP32...",
    yieldForecast: "Crop Yield Forecast",
    rainfallAlert: "Rainfall Alert",
    controlCenter: "Admin Dashboard",
    totalEnrolled: "Total Enrolled",
    pendingApprovals: "Pending Approvals",
    iotNodes: "IoT Nodes",
    askAnything: "Ask me anything about farming...",
    uploadLeaf: "Upload Leaf Photo",
    analyzeDisease: "Analyze Disease",
    marketIntel: "Market Intelligence",
    intelligenceBrief: "Intelligence Brief",
    verifiedSources: "Verified Web Sources",
    runAnalysis: "Run Analysis",
    expertAnalysis: "Expert Analysis",
    identity: "Identity",
    phone: "Phone",
    status: "Status",
    actions: "Actions",
    loginPlaceholder: "Enter 'admin' or phone number",
    passwordPlaceholder: "••••••••",
    newToNetwork: "New to the network?",
    applyNow: "Apply Now",
    quickAdmin: "Quick Admin Login",
    manualEntry: "Manual Entry",
    iotAuto: "IoT Auto",
    predictCrops: "Predict Best Crops",
    enterValues: "Enter Soil Parameters",
    nLevel: "Nitrogen (N)",
    pLevel: "Phosphorus (P)",
    kLevel: "Potassium (K)",
    phLevel: "Soil pH",
    moistureLevel: "Moisture (%)",
    tempLevel: "Temperature (°C)",
    fullName: "Full Name",
    farmArea: "Farm Area (Acres)",
    location: "Village / Location",
    submitApplication: "Submit Application",
    backToLogin: "Back to Login",
    appSuccess: "Application Submitted!",
    appSuccessMsg: "Our team will verify your details. Please save your login credentials below.",
    applyTitle: "Join the Network",
    generatePass: "Generate Password",
    yourLoginPass: "Your Password"
  },
  hi: {
    appName: "एग्रीस्मार्ट AI",
    tagline: "परिशुद्ध खेती की नई परिभाषा",
    launch: "डैशबोर्ड शुरू करें",
    health: "खेत स्वास्थ्य",
    doctor: "फसल डॉक्टर",
    predictor: "पूर्वानुमान",
    market: "बाजार",
    advisor: "सलाहकार",
    overview: "डैशबोर्ड",
    farmers: "किसान",
    campaigns: "अभियान",
    repository: "भंडार",
    nitrogen: "नाइट्रोजन",
    phosphorus: "फास्फोरस",
    potassium: "पोटेशियम",
    soilPh: "मिट्टी का pH",
    moisture: "नमी",
    temp: "तापमान",
    humidity: "आर्द्रता",
    sync: "IoT सेंसर सिंक करें",
    syncing: "ESP32 जोड़ रहा है...",
    yieldForecast: "फसल पैदावार अनुमान",
    rainfallAlert: "बारिश की चेतावनी",
    controlCenter: "व्यवस्थापक डैशबोर्ड",
    totalEnrolled: "कुल नामांकित",
    pendingApprovals: "लंबित अनुमोदन",
    iotNodes: "IoT नोड्स",
    askAnything: "खेती के बारे में कुछ भी पूछें...",
    uploadLeaf: "पत्ते की फोटो अपलोड करें",
    analyzeDisease: "रोग का विश्लेषण करें",
    marketIntel: "बाजार सूचना",
    intelligenceBrief: "बाजार विवरण",
    verifiedSources: "सत्यापित स्रोत",
    runAnalysis: "विश्लेषण चलाएं",
    expertAnalysis: "विशेषज्ञ विश्लेषण",
    identity: "पहचान",
    phone: "फोन",
    status: "स्थिति",
    actions: "कार्य",
    loginPlaceholder: "'admin' या फोन नंबर डालें",
    passwordPlaceholder: "••••••••",
    newToNetwork: "नेटवर्क में नए हैं?",
    applyNow: "अभी आवेदन करें",
    quickAdmin: "त्वरित व्यवस्थापक लॉगिन",
    manualEntry: "मैनुअल प्रविष्टि",
    iotAuto: "IoT ऑटो",
    predictCrops: "सर्वोत्तम फसलों का अनुमान",
    enterValues: "मिट्टी के पैरामीटर दर्ज करें",
    nLevel: "नाइट्रोजन (N)",
    pLevel: "फास्फोरस (P)",
    kLevel: "पोटेशियम (K)",
    phLevel: "मिट्टी का pH",
    moistureLevel: "नमी (%)",
    tempLevel: "तापमान (°C)",
    fullName: "पूरा नाम",
    farmArea: "खेत का क्षेत्रफल (एकड़)",
    location: "गाँव / स्थान",
    submitApplication: "आवेदन जमा करें",
    backToLogin: "लॉगिन पर वापस जाएं",
    appSuccess: "आवेदन जमा हो गया!",
    appSuccessMsg: "हमारी टीम विवरण की जांच करेगी। कृपया अपनी लॉगिन जानकारी सहेजें।",
    applyTitle: "नेटवर्क में शामिल हों",
    generatePass: "पासवर्ड बनाएं",
    yourLoginPass: "आपका पासवर्ड"
  },
  mr: {
    appName: "एग्रीस्मार्ट AI",
    tagline: "अचूक शेतीचे नवे युग",
    launch: "डॅशबोर्ड सुरू करा",
    health: "शेती आरोग्य",
    doctor: "पीक डॉक्टर",
    predictor: "अंदाज यंत्र",
    market: "बाजार",
    advisor: "सल्लागार",
    overview: "डॅशबोर्ड",
    farmers: "शेतकरी",
    campaigns: "मोहीम",
    repository: "कोठार",
    nitrogen: "नायट्रोजन",
    phosphorus: "फॉस्फरस",
    potassium: "पोटॅशियम",
    soilPh: "मातीचा pH",
    moisture: "ओलावा",
    temp: "तापमान",
    humidity: "हवेतील दमटपणा",
    sync: "IoT सेन्सर सिंक करा",
    syncing: "ESP32 जोडत आहे...",
    yieldForecast: "उत्पन्नाचा अंदाज",
    rainfallAlert: "पावसाचा इशारा",
    controlCenter: "ऍडमिन डॅशबोर्ड",
    totalEnrolled: "एकूण नोंदणी",
    pendingApprovals: "प्रलंबित अर्ज",
    iotNodes: "IoT नोड्स",
    askAnything: "शेतीबद्दल काहीही विचारा...",
    uploadLeaf: "पानाचे फोटो अपलोड करा",
    analyzeDisease: "रोगाचे विश्लेषण करा",
    marketIntel: "बाजार माहिती",
    intelligenceBrief: "बाजार अहवाल",
    verifiedSources: "तपासलेले स्रोत",
    runAnalysis: "विश्लेषण करा",
    expertAnalysis: "तज्ज्ञ विश्लेषण",
    identity: "ओळख",
    phone: "फोन",
    status: "स्थिती",
    actions: "कृती",
    loginPlaceholder: "'admin' किंवा फोन नंबर टाका",
    passwordPlaceholder: "••••••••",
    newToNetwork: "नेटवर्कवर नवीन आहात?",
    applyNow: "आता अर्ज करा",
    quickAdmin: "ऍडमिन लॉगिन",
    manualEntry: "मॅन्युअल माहिती",
    iotAuto: "IoT ऑटो",
    predictCrops: "उत्तम पिकांचा अंदाज",
    enterValues: "मातीचे घटक प्रविष्ट करा",
    nLevel: "नायट्रोजन (N)",
    pLevel: "फॉस्फरस (P)",
    kLevel: "पोटॅशियम (K)",
    phLevel: "मातीचा pH",
    moistureLevel: "ओलावा (%)",
    tempLevel: "तापमान (°C)",
    fullName: "पूर्ण नाव",
    farmArea: "शेती क्षेत्र (एकर)",
    location: "गाव / ठिकाण",
    submitApplication: "अर्ज सादर करा",
    backToLogin: "लॉगिनवर परत जा",
    appSuccess: "अर्ज यशस्वीरित्या सादर झाला!",
    appSuccessMsg: "आमची टीम माहितीची पडताळणी करेल. कृपया लॉगिन तपशील सेव्ह करा.",
    applyTitle: "नेटवर्कमध्ये सामील व्हा",
    generatePass: "पासवर्ड तयार करा",
    yourLoginPass: "तुमचा पासवर्ड"
  }
};
